In [1]:
import pandas as pd

df = pd.read_csv('GlobalWeatherRepository.csv')

In [2]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [3]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='str')

In [8]:
df['date'] = pd.to_datetime(df['last_updated']).dt.date.drop(columns=['last_updated'])
df['date'].head()

0    2024-05-16
1    2024-05-16
2    2024-05-16
3    2024-05-16
4    2024-05-16
Name: date, dtype: object

In [18]:
unique_dates = pd.DataFrame({'date': df['date'].unique()})
unique_dates.to_csv('unique_dates.csv', index=False)
unique_dates.head()

         date
0  2024-05-16
1  2024-05-17
2  2024-05-18
3  2024-05-19
4  2024-05-20

In [19]:
unique_df = df.groupby(['latitude', 'longitude']).first().reset_index()[['latitude', 'longitude']]
unique_df.to_csv('unique_locations.csv', index=False)
print (f'shape: {unique_df.shape}')
unique_df.head()

shape: (439, 2)

   latitude  longitude
0  -41.3000   174.7800
1  -41.3000   174.7833
2  -37.8200   144.9700
3  -35.2833   149.2167
4  -35.2800   149.2200

In [32]:
mask = (df['latitude'] == -41.3000) & (df['longitude'] == 174.7800)
dates = pd.to_datetime(df.loc[mask, 'date'])  # Convert to datetime

print(f"Start: {dates.min().date()}")
print(f"End: {dates.max().date()}")

Start: 2024-05-16
End: 2024-10-02